#%RAML 1.0 NamedExample
value:
    id: "1"
    applicantName: aniket
    dateOfApplication: "10-12-2021"
    jobId: "12"
    applicantType: fresher
    applicationStatus: active
    onlineTestStatus: pass
    onlineTestEvaluation: pass
    score: "150"
    locationPreference1: hyderabad
    locationPreference2: chennai
    locationPreference3: bengaluru
    contactNumber: "9076543210"
    emailId: abc@gmail.com
    currentLocation: hyderabad
    qualification: B-tech
    collegeName: xyz
    passOutYear: "2019"
    programmingSkills: java,python
    experience: "2"
    designation: senior consultant
    expInCC: senior
    noticePeriod: 3months
    openForRelocation: hyderabad
    currentSalary: "80000"
    expectedSalary: "100000"
    currentRound: T.R Round
    interviewPanelist: H.R
    comments: good performance

