#%RAML 1.0 DataType
type: object
properties:
  
  applicantId?: string | nil
  applicantName: string | nil
  dateOfApplication?: string | nil
  jobId: string | nil
  applicantType: string | nil
  applicationStatus?: string | nil
  onlineTestStatus?: string | nil
  onlineTestEvaluation?: string | nil
  score?: string | nil
  locationPreference1: string | nil
  locationPreference2: string | nil
  locationPreference3: string | nil
  contactNumber: string | nil
  emailId: string | nil
  currentLocation: string | nil
  qualification: string | nil
  collegeName: string | nil
  passOutYear: string | nil
  programmingSkills: string | nil
  experience?: string | nil
  designation?: string | nil
  expInCC?: string | nil
  noticePeriod?: string | nil
  openForRelocation: string | nil
  currentSalary?: string | nil
  expectedSalary?: string | nil
  currentRound?: string | nil
  interviewPanelist?: string | nil
  comments?: string | nil
  