#%RAML 1.0 DataType
type: object
properties:
  id?: string
  employeeId: string
  salary: string
  bonus: string
  hike: string
  variablePay: string
  year: string
  yearly: string
  employeeName?: string