#%RAML 1.0 DataType
type: object
properties:
  
  id?: string
  applicantName: string
  dateOfApplication: string
  jobId: string
  applicantType: string
  applicationStatus?: string
  onlineTestStatus?: string
  onlineTestEvaluation?: string
  score?: string
  locationPreference1: string
  locationPreference2: string
  locationPreference3: string
  contactNumber: string
  emailId: string
  currentLocation?: string
  qualification: string
  collegeName: string
  passOutYear: string
  programmingSkills: string
  experience?: string
  designation?: string
  expInCC?: string
  noticePeriod?: string
  openForRelocation: string
  currentSalary?: string
  expectedSalary: string
  currentRound?: string
  interviewPanelist?: string
  comments?: string
  